const { v4: uuidv4 } = require('uuid');
const bcrypt = require('bcryptjs');

// ─── IN-MEMORY DATABASE ────────────────────────────────────────────────────────
const db = {
  users: [],
  projects: [],
  tasks: [],
  activities: [],
};

// ─── ROLES ────────────────────────────────────────────────────────────────────
const ROLES = {
  ADMIN_PLATFORM: 'admin_platform',
  ADMIN_COMPANY: 'admin_company',
  MANAGER_AREA: 'manager_area',
  PROJECT_MANAGER: 'project_manager',
  EMPLOYEE: 'employee',
};

const ROLE_LABELS = {
  admin_platform: 'Admin da Plataforma',
  admin_company: 'Admin da Empresa',
  manager_area: 'Gestor de Área',
  project_manager: 'Gerente de Projeto',
  employee: 'Funcionário',
};

// ─── SEED DATA ────────────────────────────────────────────────────────────────
async function seedDatabase() {
  const password = await bcrypt.hash('123456', 10);

  db.users = [
    {
      id: 'u1',
      name: 'Admin Sistema',
      email: 'admin@taskflow.com',
      cpf: '000.000.000-00',
      password,
      role: ROLES.ADMIN_PLATFORM,
      department: 'TI',
      avatar: 'AS',
      active: true,
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'u2',
      name: 'Carlos Mendes',
      email: 'carlos@empresa.com',
      cpf: '111.111.111-11',
      password,
      role: ROLES.ADMIN_COMPANY,
      department: 'Diretoria',
      avatar: 'CM',
      active: true,
      createdAt: new Date('2024-01-05'),
    },
    {
      id: 'u3',
      name: 'Ana Gestora',
      email: 'ana@empresa.com',
      cpf: '222.222.222-22',
      password,
      role: ROLES.MANAGER_AREA,
      department: 'Desenvolvimento',
      avatar: 'AG',
      active: true,
      createdAt: new Date('2024-01-10'),
    },
    {
      id: 'u4',
      name: 'Bruno Gerente',
      email: 'bruno@empresa.com',
      cpf: '333.333.333-33',
      password,
      role: ROLES.PROJECT_MANAGER,
      department: 'Desenvolvimento',
      avatar: 'BG',
      active: true,
      createdAt: new Date('2024-01-15'),
    },
    {
      id: 'u5',
      name: 'Lucia Dev',
      email: 'lucia@empresa.com',
      cpf: '444.444.444-44',
      password,
      role: ROLES.EMPLOYEE,
      department: 'Desenvolvimento',
      avatar: 'LD',
      active: true,
      createdAt: new Date('2024-02-01'),
    },
    {
      id: 'u6',
      name: 'Pedro Silva',
      email: 'pedro@empresa.com',
      cpf: '555.555.555-55',
      password,
      role: ROLES.EMPLOYEE,
      department: 'Design',
      avatar: 'PS',
      active: true,
      createdAt: new Date('2024-02-10'),
    },
    {
      id: 'u7',
      name: 'Mariana Costa',
      email: 'mariana@empresa.com',
      cpf: '666.666.666-66',
      password,
      role: ROLES.EMPLOYEE,
      department: 'QA',
      avatar: 'MC',
      active: false,
      createdAt: new Date('2024-03-01'),
    },
  ];

  db.projects = [
    {
      id: 'p1',
      name: 'Sistema de Gestão v2.0',
      description: 'Refatoração e melhoria do sistema de gestão interno',
      status: 'em_progresso',
      priority: 'alta',
      progress: 65,
      startDate: new Date('2024-01-15'),
      endDate: new Date('2026-03-15'),
      managerId: 'u4',
      members: ['u4', 'u5', 'u6', 'u3', 'u2', 'u7', 'u1'],
      createdAt: new Date('2024-01-15'),
      createdBy: 'u2',
    },
    {
      id: 'p2',
      name: 'Redesign Dashboard',
      description: 'Novo visual do painel administrativo com UX aprimorado',
      status: 'em_progresso',
      priority: 'media',
      progress: 40,
      startDate: new Date('2024-02-01'),
      endDate: new Date('2026-03-20'),
      managerId: 'u4',
      members: ['u4', 'u6', 'u5'],
      createdAt: new Date('2024-02-01'),
      createdBy: 'u3',
    },
    {
      id: 'p3',
      name: 'API Integração',
      description: 'Integração com sistemas externos via API REST',
      status: 'planejamento',
      priority: 'alta',
      progress: 15,
      startDate: new Date('2024-03-01'),
      endDate: new Date('2026-03-30'),
      managerId: 'u3',
      members: ['u3', 'u5'],
      createdAt: new Date('2024-03-01'),
      createdBy: 'u2',
    },
    {
      id: 'p4',
      name: 'Mobile App',
      description: 'Aplicativo mobile para gestão em campo',
      status: 'concluido',
      priority: 'baixa',
      progress: 100,
      startDate: new Date('2023-10-01'),
      endDate: new Date('2024-01-01'),
      managerId: 'u4',
      members: ['u4', 'u5', 'u6'],
      createdAt: new Date('2023-10-01'),
      createdBy: 'u2',
    },
  ];

  db.tasks = [
    {
      id: 't1',
      title: 'Revisar código do módulo de autenticação',
      description: 'Revisar e refatorar o código de autenticação JWT',
      projectId: 'p1',
      assigneeId: 'u5',
      status: 'em_andamento',
      priority: 'alta',
      dueDate: new Date('2026-03-10'),
      createdAt: new Date('2024-01-20'),
      createdBy: 'u4',
    },
    {
      id: 't2',
      title: 'Criar wireframes da nova interface',
      description: 'Desenvolver wireframes de alta fidelidade no Figma',
      projectId: 'p2',
      assigneeId: 'u6',
      status: 'em_andamento',
      priority: 'media',
      dueDate: new Date('2026-03-20'),
      createdAt: new Date('2024-02-05'),
      createdBy: 'u4',
    },
    {
      id: 't3',
      title: 'Documentar API endpoints',
      description: 'Criar documentação completa dos endpoints no Swagger',
      projectId: 'p3',
      assigneeId: 'u5',
      status: 'a_fazer',
      priority: 'alta',
      dueDate: new Date('2026-03-25'),
      createdAt: new Date('2024-03-05'),
      createdBy: 'u3',
    },
    {
      id: 't4',
      title: 'Testar fluxo de recuperação de senha',
      description: 'Executar testes E2E do fluxo de recuperação de senha',
      projectId: 'p1',
      assigneeId: 'u7',
      status: 'concluido',
      priority: 'baixa',
      dueDate: new Date('2026-02-28'),
      createdAt: new Date('2024-02-20'),
      createdBy: 'u4',
    },
    {
      id: 't5',
      title: 'Implementar dashboard de métricas',
      description: 'Criar componentes de gráficos e KPIs no dashboard',
      projectId: 'p2',
      assigneeId: 'u6',
      status: 'a_fazer',
      priority: 'alta',
      dueDate: new Date('2026-04-10'),
      createdAt: new Date('2024-02-10'),
      createdBy: 'u3',
    },
    {
      id: 't6',
      title: 'Configurar CI/CD pipeline',
      description: 'Configurar pipeline de integração e deploy contínuo',
      projectId: 'p1',
      assigneeId: 'u5',
      status: 'a_fazer',
      priority: 'media',
      dueDate: new Date('2026-04-05'),
      createdAt: new Date('2024-03-10'),
      createdBy: 'u4',
    },
    {
      id: 't7',
      title: 'Migrar banco de dados',
      description: 'Migrar dados do sistema legado para nova estrutura',
      projectId: 'p1',
      assigneeId: 'u5',
      status: 'concluido',
      priority: 'alta',
      dueDate: new Date('2024-03-01'),
      createdAt: new Date('2024-02-01'),
      createdBy: 'u2',
    },
    {
      id: 't8',
      title: 'Revisar contratos de API',
      description: 'Verificar e atualizar contratos dos serviços externos',
      projectId: 'p3',
      assigneeId: 'u3',
      status: 'em_andamento',
      priority: 'media',
      dueDate: new Date('2026-04-15'),
      createdAt: new Date('2024-03-08'),
      createdBy: 'u3',
    },
  ];

  db.activities = [
    { id: 'a1', userId: 'u5', action: 'concluiu a tarefa', target: 'Migrar banco de dados', projectId: 'p1', createdAt: new Date(Date.now() - 3600000) },
    { id: 'a2', userId: 'u6', action: 'atualizou o status de', target: 'Criar wireframes da nova interface', projectId: 'p2', createdAt: new Date(Date.now() - 7200000) },
    { id: 'a3', userId: 'u4', action: 'criou o projeto', target: 'API Integração', projectId: 'p3', createdAt: new Date(Date.now() - 86400000) },
    { id: 'a4', userId: 'u3', action: 'adicionou tarefa', target: 'Documentar API endpoints', projectId: 'p3', createdAt: new Date(Date.now() - 172800000) },
    { id: 'a5', userId: 'u2', action: 'aprovou o projeto', target: 'Sistema de Gestão v2.0', projectId: 'p1', createdAt: new Date(Date.now() - 259200000) },
  ];
}

module.exports = { db, ROLES, ROLE_LABELS, seedDatabase };
